// flow-typed signature: ee539bc5a0d756e58541103fe73b0725
// flow-typed version: <<STUB>>/firebase_v5.0.3/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'firebase'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'firebase' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

declare module 'firebase/firebase-app' {
  declare module.exports: any;
}

declare module 'firebase/firebase-auth' {
  declare module.exports: any;
}

declare module 'firebase/firebase-database' {
  declare module.exports: any;
}

declare module 'firebase/firebase-firestore' {
  declare module.exports: any;
}

declare module 'firebase/firebase-functions' {
  declare module.exports: any;
}

declare module 'firebase/firebase-messaging' {
  declare module.exports: any;
}

declare module 'firebase/firebase-storage' {
  declare module.exports: any;
}

declare module 'firebase/firebase' {
  declare module.exports: any;
}

// Filename aliases
declare module 'firebase/firebase-app.js' {
  declare module.exports: $Exports<'firebase/firebase-app'>;
}
declare module 'firebase/firebase-auth.js' {
  declare module.exports: $Exports<'firebase/firebase-auth'>;
}
declare module 'firebase/firebase-database.js' {
  declare module.exports: $Exports<'firebase/firebase-database'>;
}
declare module 'firebase/firebase-firestore.js' {
  declare module.exports: $Exports<'firebase/firebase-firestore'>;
}
declare module 'firebase/firebase-functions.js' {
  declare module.exports: $Exports<'firebase/firebase-functions'>;
}
declare module 'firebase/firebase-messaging.js' {
  declare module.exports: $Exports<'firebase/firebase-messaging'>;
}
declare module 'firebase/firebase-storage.js' {
  declare module.exports: $Exports<'firebase/firebase-storage'>;
}
declare module 'firebase/firebase.js' {
  declare module.exports: $Exports<'firebase/firebase'>;
}
