// flow-typed signature: 8aa8deb4c7565519ffeddda55a2477f3
// flow-typed version: <<STUB>>/react-stage_v^2.0.8/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-stage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-stage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-stage/demo/client' {
  declare module.exports: any;
}

declare module 'react-stage/demo/components/elements/arrow' {
  declare module.exports: any;
}

declare module 'react-stage/demo/components/layouts/Html' {
  declare module.exports: any;
}

declare module 'react-stage/demo/components/pages/App' {
  declare module.exports: any;
}

declare module 'react-stage/demo/components/pages/AppStyles' {
  declare module.exports: any;
}

declare module 'react-stage/demo/server' {
  declare module.exports: any;
}

declare module 'react-stage/lib/react-stage.min' {
  declare module.exports: any;
}

declare module 'react-stage/src/index' {
  declare module.exports: any;
}

declare module 'react-stage/src/index.spec' {
  declare module.exports: any;
}

declare module 'react-stage/src/index.styles' {
  declare module.exports: any;
}

declare module 'react-stage/src/library' {
  declare module.exports: any;
}

declare module 'react-stage/src/utilities/dom-to-string' {
  declare module.exports: any;
}

declare module 'react-stage/src/utilities/tabbable' {
  declare module.exports: any;
}

declare module 'react-stage/tools/webpack/webpack.config.babel' {
  declare module.exports: any;
}

declare module 'react-stage/tools/webpack/webpack.config.base.babel' {
  declare module.exports: any;
}

declare module 'react-stage/tools/webpack/webpack.config.client.babel' {
  declare module.exports: any;
}

declare module 'react-stage/tools/webpack/webpack.config.lib.babel' {
  declare module.exports: any;
}

declare module 'react-stage/tools/webpack/webpack.config.server.babel' {
  declare module.exports: any;
}

declare module 'react-stage/tools/webpack/webpack.config.umd.babel' {
  declare module.exports: any;
}

declare module 'react-stage/umd/index.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-stage/demo/client.js' {
  declare module.exports: $Exports<'react-stage/demo/client'>;
}
declare module 'react-stage/demo/components/elements/arrow.js' {
  declare module.exports: $Exports<'react-stage/demo/components/elements/arrow'>;
}
declare module 'react-stage/demo/components/layouts/Html.js' {
  declare module.exports: $Exports<'react-stage/demo/components/layouts/Html'>;
}
declare module 'react-stage/demo/components/pages/App.js' {
  declare module.exports: $Exports<'react-stage/demo/components/pages/App'>;
}
declare module 'react-stage/demo/components/pages/AppStyles.js' {
  declare module.exports: $Exports<'react-stage/demo/components/pages/AppStyles'>;
}
declare module 'react-stage/demo/server.js' {
  declare module.exports: $Exports<'react-stage/demo/server'>;
}
declare module 'react-stage/lib/react-stage.min.js' {
  declare module.exports: $Exports<'react-stage/lib/react-stage.min'>;
}
declare module 'react-stage/src/index.js' {
  declare module.exports: $Exports<'react-stage/src/index'>;
}
declare module 'react-stage/src/index.spec.js' {
  declare module.exports: $Exports<'react-stage/src/index.spec'>;
}
declare module 'react-stage/src/index.styles.js' {
  declare module.exports: $Exports<'react-stage/src/index.styles'>;
}
declare module 'react-stage/src/library.js' {
  declare module.exports: $Exports<'react-stage/src/library'>;
}
declare module 'react-stage/src/utilities/dom-to-string.js' {
  declare module.exports: $Exports<'react-stage/src/utilities/dom-to-string'>;
}
declare module 'react-stage/src/utilities/tabbable.js' {
  declare module.exports: $Exports<'react-stage/src/utilities/tabbable'>;
}
declare module 'react-stage/tools/webpack/webpack.config.babel.js' {
  declare module.exports: $Exports<'react-stage/tools/webpack/webpack.config.babel'>;
}
declare module 'react-stage/tools/webpack/webpack.config.base.babel.js' {
  declare module.exports: $Exports<'react-stage/tools/webpack/webpack.config.base.babel'>;
}
declare module 'react-stage/tools/webpack/webpack.config.client.babel.js' {
  declare module.exports: $Exports<'react-stage/tools/webpack/webpack.config.client.babel'>;
}
declare module 'react-stage/tools/webpack/webpack.config.lib.babel.js' {
  declare module.exports: $Exports<'react-stage/tools/webpack/webpack.config.lib.babel'>;
}
declare module 'react-stage/tools/webpack/webpack.config.server.babel.js' {
  declare module.exports: $Exports<'react-stage/tools/webpack/webpack.config.server.babel'>;
}
declare module 'react-stage/tools/webpack/webpack.config.umd.babel.js' {
  declare module.exports: $Exports<'react-stage/tools/webpack/webpack.config.umd.babel'>;
}
declare module 'react-stage/umd/index.min.js' {
  declare module.exports: $Exports<'react-stage/umd/index.min'>;
}
